# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodApp
  pod 'Moya/RxSwift', '~> 14.0'
  pod 'RxSwift', '5.1.1'
  pod 'RxCocoa', '5.1.1'
end
